version: '3.7'

services:
  custom-nginx:
    container_name: custom-nginx
    image: nginx:latest
    volumes:
      - ./logs:/etc/nginx/logs:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d/:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      # tarlao.fr
      - ./public-siteperso:/usr/share/nginx/html:ro
      # calibreo.it
      - ./public-network-backend:/usr/share/nginx/backend:ro
      - ./public-network-frontend:/usr/share/nginx/frontend:ro
    ports:
      - 80:80
      - 90:90
      - 443:443
    healthcheck:
      test: curl -f http://localhost:90/nginx-health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1500M'
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - calibreo
      - anthony

  custom-certbot:
    image: certbot/certbot:latest
    container_name: custom-certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  calibreo:
    external: true
  anthony:
    external: true